version: '3.4'

services:
  compliantapi:
    image: ${DOCKER_REGISTRY-}compliantapi
    build:
      context: .
      dockerfile: CompliantAPI/Dockerfile
    ports:
    - "7015:443"
  compliant-frontend:
     image: ${DOCKER_REGISTRY-}compliant-frontend
     build:
        context: ./Compliant-Frontend
        dockerfile: Dockerfile
     ports:
     - "7016:80"
     depends_on:
     - compliantapi